name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Download Python installer
        run: python python_last_version.py

      
      - name: Install Inno Setup
        run: |
          choco install innosetup -y

      - name: Create deps directory and download wheels
        run: |
          mkdir -p deps
          pip download -d deps pyqt5 numpy

      - name: Build installer
        run: |
          iscc /Q- simpleInstallerWin10x64.iss /O"output"

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            output/*.exe
          draft: false
          prerelease: false
          body_path: RELEASE.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
